name: Run Telegram Bot

on:
  push:
    branches:
      - main  # Thay 'main' bằng tên của nhánh bạn muốn trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install python-telegram-bot requests pytz

      - name: Run Telegram Bot
        run: |
          while true; do
            python quayxu.py  # Thay 'quayxu.py' bằng tên file của bạn
            sleep 10  # Thời gian nghỉ giữa các lần chạy, có thể điều chỉnh
          done
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.QUAY_XU_BOT }}
          # Thêm các biến môi trường khác nếu cần thiết
